ini_ammo            = ballistics_utils.ini_ammo
math_random = math.random
--grenade handlers

-- m209 cluster

local bomb_min_force = 2000
local bomb_force = 3000
function detonate(item_id)
    local bomb = get_object_by_id(item_id)
    if bomb then
        bomb:explode(0)
    end
    return true
end
function bomb_scatter(item_id)
    local bomb = level.object_by_id(item_id)
    if bomb then
        bomb:get_physics_shell():apply_force(
            bomb_min_force + (random_float(-1, 1) * bomb_force * 5),
            (bomb_min_force + (math_random() * bomb_force * 5)),
            bomb_min_force + (random_float(-1, 1) * bomb_force * 5))
        CreateTimeEvent(item_id, math_random(10), 0.2 + 1.5 * math_random(), detonate, item_id)
        return true
    end
    return false
end
local cluster_particle
function cluster_bomb(position, ammo, wpn_id)
    local bomb_type = ini_ammo:r_string_ex(ammo, "bomb_type")
	printf("Bomb Handlers - Bomb Type: %s", bomb_type)
    if not bomb_type then return end
    local bomb_count = ini_ammo:r_float_ex(ammo, "bomb_count") or 1
	printf("Bomb Handlers - Bomb Count: %s", bomb_count)
	
    local lvid = db.actor:level_vertex_id()
    local gvid = db.actor:game_vertex_id()
    if not cluster_particle then cluster_particle = particles_object("explosions\\explosion_03") end
    cluster_particle:play_at_pos(position)
    for i = 1, bomb_count do
        local pos = vector():set(position.x, position.y, position.z)
        local dir = vector():set(random_float(-1, 1), math_random(), random_float(-1, 1))
        pos.x = pos.x + dir.x
        pos.y = pos.y + dir.y + 1
        pos.z = pos.z + dir.z
        local bomb = alife_create_item(bomb_type, {pos, lvid, gvid})
        CreateTimeEvent(bomb.id, bomb.id, 0, bomb_scatter, bomb.id)
    end
end

local fire_particle, fire_particle2

local burn_min = 18
local burn_max = 60
local burn_radius = 25

function ignite(position, ammo, wpn_id)

    if not fire_particle then fire_particle = particles_object("explosions\\effects\\expl_smoke_big_veh") end
    fire_particle:play_at_pos(position)
    if not fire_particle2 then fire_particle2 = particles_object("explosions\\effects\\expl_distortion") end
    ballistics_utils.play_sound_distance("incendiary", db.actor:position():distance_to(position))
    fire_particle:play_at_pos(position)
    fire_particle2:play_at_pos(position)
    level.iterate_nearest(position, burn_radius, function(obj)
        if obj and obj:id() ~= AC_ID and obj:alive() then
			if string.find(obj:name(), "legs") then return end	-- Avoid first-person legs
            arti_handlers.burn_npc(obj, 11, math_random(burn_min, burn_max))
        end
    end)
end
